service: sample-application 
disabledDeprecations: '*' 
configValidationMode: error 
provider: 
  name: aws 
  runtime: nodejs14.x 
  stage: dev 
  region: ap-south-1
  memorySize: 128 
plugins:
  - serverless-offline
  - serverless-domain-manager
custom:
  customDomain:
    domainName: apiv3.eventwhiz.site
    certificateName: 'eventwhiz.site'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
functions: 
  app: 
    handler: app.handler 
    events: 
      - http: 
          path: / 
          method: ANY 
          cors: true 
      - http: 
          path: /{proxy+} 
          method: ANY 
          cors: true 